repos:
  - repo: local
    hooks:

    - id: black
      name: format
      entry: black
      types: [python]
      stages: [commit]
      language: system
      
    - id: flake8
      name: lint
      entry: flake8
      types: [python]
      stages: [commit]
      language: system

    - id: pydocstyle
      name: docstyle
      entry: pydocstyle
      types: [python]
      stages: [commit]
      language: system
      exclude: ^tests/